spring:
  h2:
    console:
      enabled: true
      path: /h2
  thymeleaf:
    prefix=classpath: templates/
    suffix: .html
    check-template-location: true
    cache: false
  mvc:
    static-path-pattern: "/css/**"
  datasource:
    url: jdbc:h2:tcp://localhost/~/socialMatchingWeb
    username: hongcheol
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.springframework.web: DEBUG

# org.hibernate.type: trace
server:
  port: 8000
